Kitware/eSimMon

client/src/components/ImageGallery.vue
client/src/scss/gallery.scss

* better lazy-loading behavior
* play/pause button

improvements to image gallery

---

client/package.json
client/src/App.vue
client/src/components/ImageGallery.vue
client/src/scss/gallery.scss
client/yarn.lock

* Move navigation panel to the left side
* Make a 2x2 grid of galleris so we can more easily compare variables
* Use drag & drop to select variables for viewing
* Synchronize playback across variables with a single set of controls

Improve look & feel of adios dashboard

---

client/src/App.vue
client/src/components/ImageGallery.vue
ingest/adash/cli/mock/__init__.py
ingest/adash/cli/watch/__init__.py

Smoothing out our demo in light of our recent test data acquisition.

More tweaks

---

client/src/App.vue
client/src/components/ImageGallery.vue
client/src/scss/gallery.scss

Looking back it looks like the margin fix accidentally got lost when fixing a previous merge conflict. Add the styling back in.

Remove margins from plots pane

---

client/src/App.vue
client/src/components/ImageGallery.vue
client/src/scss/gallery.scss

Using styling updates made in #35 
Handle either images or json files for plots

Allow images

---

client/README.md
client/public/index.html

Update the name from adios-dashboard to eSimMon

---

client/package.json
client/src/main.js

Allow add authenticateWithCredentials is using api root

Allow api url and folder to be provided a build time

---

client/package.json
client/src/App.vue
client/src/components/GirderFileManager.vue
client/src/components/ImageGallery.vue
client/src/main.js
devops/docker/flask/Dockerfile
flask/README.md
flask/requirements.txt
flask/src/server.py

Very rough first pass at flask service, this will need further iterations to complete. Currently still using some hard-coded data for ease of testing.

Create basic flask service for creating movies from images

---

devops/docker/girder/Dockerfile

Install eSimMon plugin in Girder container

---

client/src/components/GirderFileManager.vue
client/src/components/ImageGallery.vue

Prevent download movie context menu for Plotly plots

---

client/src/App.vue

Fixes the issue with the dashboard not loading correctly (initially or on refresh) after the docker stack is brought down and back up.

Ensure default location is correct on every load

---

client/src/App.vue
client/src/components/ImageGallery.vue

Handle the case where a parameter may not have an image for every time step.

Missing timesteps

---

client/package.json
client/yarn.lock

Update dependencies to address security alerts

---

client/src/components/GirderFileManager.vue
client/src/components/ImageGallery.vue

Remove unused import and variable to fix compilation errors

---

README.md

Adds instructions for using the EFFIS data

Add instructions for the EFFIS workflow

---

devops/docker/movie.env

Correct the CORS_DOMAIN variable

---

client/src/App.vue

Fix console errors

---

client/src/App.vue

Fix typo id => _id

---

devops/docker/girder/Dockerfile

https://github.com/cherrypy/cheroot/pull/277

Update cheroot to include timeout fix

---

client/src/App.vue
flask/src/server.py

- Generate movies for `png` and `svg` files
- Add toast notifications to indicate when

Update movie generation

---

client/src/components/widgets/LoadDialog/script.js
client/src/components/widgets/LoadDialog/template.html
girder/esimmon_plugin/esimmon_plots/models/view.py

Add the first and last name of the creator to both the view model and the apply view table.

View table update

---

client/src/components/core/App/script.js
client/src/components/core/App/template.html
client/src/components/widgets/ImageGallery/script.js
client/src/components/widgets/RangeDialog/index.vue
client/src/components/widgets/RangeDialog/script.js
client/src/components/widgets/RangeDialog/template.html

Allow users to set and remove the global range for dynamic plots.

Global range

---

docs/data.md
docs/views.md

Reflects changes in #111 and #112

Update the docs to reflect most recent changes

---

client/src/components/core/App/template.html

This fixes the issue seen with running in development mode.

Add missing closing tag

---

client/src/components/widgets/ImageGallery/template.html

This is causing issues in development mode and it not necessary.

Remove outer template tag

---

client/src/components/widgets/ImageGallery/script.js
client/src/components/widgets/RenderWindow/script.js

Start improvements on zoom scale calculation

---

client/src/components/widgets/ImageGallery/script.js
client/src/components/widgets/RenderWindow/script.js

Make sure the renderer is completely removed from the render window when a vtk plot is removed

Make sure renderer is completely removed

---

client/src/scss/gallery.scss

Fix playback controls container sizing

---

client/src/components/widgets/ImageGallery/script.js

Item id may not have changed but available time steps should still be reset

Always reset the loadedTimestepData on template load

---

.pre-commit-config.yaml
client/src/components/core/App/script.js
client/src/components/core/App/template.html
client/src/components/widgets/ContextMenu/index.vue
client/src/components/widgets/ContextMenu/script.js
client/src/components/widgets/ContextMenu/template.html
client/src/components/widgets/GirderFileManager/script.js
client/src/components/widgets/GirderFileManager/template.html
client/src/components/widgets/ImageGallery/script.js
client/src/components/widgets/ImageGallery/template.html
client/src/scss/gallery.scss
client/src/store/plots.js
client/src/store/ui.js
devops/docker/fastapi/Dockerfile
fastapi/app/api/api_v1/api.py
fastapi/app/api/api_v1/endpoints/colormap.py
fastapi/app/api/api_v1/endpoints/images.py
fastapi/app/api/api_v1/endpoints/mesh.py
fastapi/app/api/api_v1/endpoints/movie.py
fastapi/app/api/api_v1/endpoints/plotly.py
fastapi/app/api/api_v1/endpoints/variables.py
fastapi/requirements.txt
fastapi/scripts/offscreen_rendering.sh

~WIP - Currently still needs:~

Save plots

---

client/src/components/widgets/ImageGallery/script.js
fastapi/app/api/api_v1/endpoints/images.py

If log scaling has been applied to a plotly plot make sure it is used for the saved image(s)/movie(s)

Apply log scaling to saved images if set

---

devops/docker/fastapi/Dockerfile

Our container was segfaulting on k8, using a newer version of mesa seems to fix the issue.

Build our own version of mesa

---

ingest/esimmon/cli/watch/__init__.py

1 sec seems a little aggressive ...

Use shot poll interval while waiting for shots/index.json to appear

---

client/src/components/widgets/ContextMenu/template.html
client/src/components/widgets/PlotlyPlot/script.js
client/src/components/widgets/Plots/script.js
client/src/components/widgets/Plots/template.html
client/src/components/widgets/VTKPlot/script.js
client/src/utils/constants.js
client/src/utils/vtkPlotStyling.js
fastapi/app/api/api_v1/endpoints/colormap.py
fastapi/app/api/api_v1/endpoints/images.py
fastapi/app/api/api_v1/endpoints/mesh.py
fastapi/app/api/api_v1/endpoints/variables.py

We are currently able to plot the data for the 2D flux plots, however this branch is currently still a WIP.
Original png:
The plot data looks accurate now and we can hack the scaling to keep the plot square, but there is still the issue of the x axis displaying the scaled values rather than the original data. This is an issue that I haven't found a clear solution for yet.
This branch also still needs to add back-end support for downloading flux plot images and movies.

Add basic support for the 2D flux plots

---

client/src/components/core/App/script.js
client/src/components/widgets/PlotlyPlot/script.js
client/src/components/widgets/Plots/script.js
client/src/components/widgets/VTKPlot/script.js

Minor bugs

---

client/package.json
client/yarn.lock

Supports [dependabot issue](https://github.com/Kitware/eSimMon/security/dependabot/34)

Bump node-sass version

---

client/.eslintrc.js
client/src/components/widgets/Plots/script.js
client/src/utils/plotFetcher.ts

Run pre-commit and clean up some warnings

Pre commit and warnings

---

client/src/components/core/App/script.js
client/src/components/widgets/LoadDialog/script.js
client/src/components/widgets/LoadDialog/template.html
client/src/components/widgets/Plots/script.js

Template loading was out of sync with the expectations of  loading a view. Add updated keys/values for setting up plots.
Also cleans up a typo and refrains from removing cached data (for now - need to be smarter about this going forward).

Template loading

---

client/src/components/widgets/PlotlyPlot/script.js
client/src/components/widgets/VTKPlot/script.js

If there is no plot for the current time step and we are just displaying the previously rendered plot do not try to re-render the same data.

Do not try to re-render if there is no new data

---

client/src/bootstrap.js
client/src/components/core/App/script.js
devops/docker/ansible/Dockerfile
devops/docker/nginx/Dockerfile

Additional updates to allow using the same images for all deployments

Simplify containers

---

.github/workflows/pre-commit.yaml
.pre-commit-config.yaml
.secrets.baseline
client/public/index.html
client/src/components/core/App/script.js
client/src/components/widgets/DownloadOptions/script.js
client/src/components/widgets/GirderDataBrowser/script.js
client/src/components/widgets/GirderFileManager/script.js
client/src/components/widgets/PlotlyPlot/script.js
client/src/components/widgets/Plots/script.js
client/src/components/widgets/RenderWindow/script.js
client/src/components/widgets/VTKPlot/script.js
client/src/store/views.js
fastapi/app/api/api_v1/endpoints/plotly.py
fastapi/app/api/api_v1/endpoints/utils.py
ingest/esimmon/cli/watch/__init__.py

Bump actions versions

---

client/src/components/widgets/ContextMenu/script.js
client/src/components/widgets/DownloadOptions/script.js
client/src/components/widgets/DownloadOptions/template.html
fastapi/app/api/api_v1/endpoints/movie.py

Allow users to set FPS for movies

---

ingest/esimmon/cli/watch/__init__.py
ingest/setup.py

As each new time step is ingested update the respective item metadata to track min/max values for the run.

Update item metadata as bpm files are ingested

---

devops/docker/ingest/Dockerfile
ingest/setup.py

Install adios2 with conda

---

devops/docker/fastapi/Dockerfile

Needed to support the generation and upload of movies for larger parameters.

Increase keep-alive time for fastapi

---

docs/schema.md
ingest/esimmon/cli/watch/__init__.py
mkdocs.yml

Add documentation on the directory structure and file schema expected in order to automatically ingest data into the dashboard.

Ingest docs

---

client/src/components/widgets/Annotations/script.js
client/src/components/widgets/Annotations/template.html
client/src/components/widgets/ContextMenu/script.js
client/src/components/widgets/ContextMenu/template.html
client/src/components/widgets/PlotlyPlot/script.js
client/src/components/widgets/PlotlyPlot/template.html
client/src/components/widgets/Plots/script.js
client/src/components/widgets/Plots/template.html
client/src/components/widgets/RangeDialog/script.js
client/src/components/widgets/RangeDialog/template.html
client/src/components/widgets/RenderWindow/script.js
client/src/components/widgets/SettingsPanel/script.js
client/src/components/widgets/VTKPlot/script.js
client/src/components/widgets/VTKPlot/template.html
client/src/scss/gallery.scss
client/src/store/plot.js
client/src/store/ui.js

1. Replace the tooltip with annotations on images
2. Add titles to VTK plots
3. Fix bugs in the zoom behavior
1. Prevents issues where the plot would sometimes slowly skew after zooming in and out
4. Update the context menu global range inputs. Users inputs override the global values from the run if they've been applied. Suggested values can also be auto populated from the global range.

Annotations

---

client/src/components/core/App/script.js
client/src/components/core/App/template.html
client/src/components/widgets/GirderFileManager/script.js
client/src/components/widgets/GirderFileManager/template.html
client/src/components/widgets/SettingsPanel/template.html
client/src/scss/gallery.scss
client/src/store/ui.js

- Always show the time step tools, even in the settings panel
- Add the ability to collapse the navigation panel

Improve nav drawer

---

client/src/components/widgets/Annotations/script.js
client/src/components/widgets/Annotations/template.html
client/src/components/widgets/PlotlyPlot/script.js
client/src/components/widgets/PlotlyPlot/template.html
client/src/components/widgets/SettingsPanel/script.js
client/src/components/widgets/SettingsPanel/template.html
client/src/components/widgets/VTKPlot/script.js
client/src/components/widgets/VTKPlot/template.html
client/src/scss/gallery.scss
client/src/store/ui.js

Add an annotation indicating the current time step per plot
