Kitware/eSimMon

client/src/App.vue
client/src/components/ImageGallery.vue
client/src/scss/gallery.scss

Previously the dashboard was hardcoded as a 2x2 grid. Now the user can add rows and columns as they see fit.
This PR also reduces the amount of screen real estate dedicated to the girder browser, and makes the playback control panel a floating, translucent section at the bottom of the page.

Make it possible to view more variables at once

---

client/src/App.vue
client/src/components/ImageGallery.vue
client/src/main.js

Based on #11, poll for new data and show it as it arrives.
@cjh1 you'll notice that this PR does simple polling instead of using Girder EventSource notifications. I tried these out but they didn't seem to fit the bill:
1) There didn't seem to be any way to configure what you'll actually get notified about.
2) Notifications seem to be disabled on data.kitware.com.

Stream new timesteps as they arrive

---

client/src/App.vue

Removing a plot was not updating the current count of loaded galleries, creating
a bug that would cause the play option to stop working. Update the number of
loaded galleries on row or column removal.

Fix bug caused by removing plots

---

client/src/App.vue
client/src/scss/gallery.scss

This fixes two of the layout issues that I noticed: the size and alignment of the slider, and margins around the plots.

Fix layout

---

client/src/App.vue
client/src/components/GirderDataBrowser.vue
client/src/components/GirderFileManager.vue
client/src/scss/gallery.scss

This PR adds in a search bar for locating parameters by name. When the dashboard is initially loaded the entire tree is searched and a master list of all parameters is made. Navigating up or down the tree and typing a name into the search bar will filter that list down. Simply clicking in the search box will display a drop-down menu of every parameter available under the current location, and the list will be filtered as the parameter name is typed.
Pressing `enter` or clicking the search icon will update the data browser table to display all parameters that match the current search criteria, and those parameters can be dragged and dropped into the plot grid as usual. The parameter names will include the current path as well in order to differentiate between any parameters that may have …

Search param list

---

client/src/scss/gallery.scss

This seems to be working for me, but even when I was collapsing the window down it was impossible for me to get the controls to be completely hidden. Nonetheless I was able to get a vertical scroll when the window and panel were shrunk down now, hopefully this solves the problem.
Fixes #65

Add a horizontal scroll bar for the left nav panel

---

README.md
devops/docker/docker-compose.watch-standalone.yml
devops/docker/ingest/Dockerfile

If the monitoring service is being run in the stack, use a docker-compose `entrypoint` to wait until Girder is available. If it is being separately, do not wait.

Create docker-compose for standalone watch service

---

devops/ansible/site.yml

This fixes a bug that made the assetstore unavailable after the stack was brought down since the volume path did not match the root path being set by the Ansible playbook.

Mount the assetstore in the correct location

---

client/src/components/ImageGallery.vue

If there is no data available for the current or any previous time steps, then use the data for the next available time step.

Handle the case of no first time step

---

.gitignore
devops/docker/girder/Dockerfile

Add the `autojoin` plugin in order to automatically assign users to groups in Girder.

Girder plugin

---

client/src/components/core/App/script.js
client/src/components/core/App/template.html
client/src/components/core/ViewControls/script.js
client/src/components/core/ViewControls/template.html
client/src/components/widgets/ImageGallery/script.js
client/src/components/widgets/LoadDialog/script.js
client/src/components/widgets/LoadDialog/template.html
client/src/components/widgets/SaveDialog/script.js
client/src/components/widgets/SaveDialog/template.html
client/src/main.js
client/src/scss/gallery.scss
client/src/utils/utilityFunctions.js
girder/esimmon_plugin/esimmon_plots/models/view.py
girder/esimmon_plugin/esimmon_plots/view.py

This PR contains a lot of new features and behaviors:
- Auto-save a default View
- Once a parameter is added the auto-save feature is enabled
- The last added parameter is used to determine which simulation and run to associate the auto-saved (i.e. "default") View with
- If a user navigates to a run with an associated default view they will shown a dialog that allows them to choose whether or not to load that default view
- When a user navigates to a new run the auto-save will stop until a new parameter is added again. This is to prevent the default view from being associated with the wrong simulation/run.
- Text has been added to the bottom of the view controls to indicate that the View is being auto-saved and when the last save happened
- Remember time step
- When a View is save …

Private views

---

client/src/components/widgets/ImageGallery/script.js

Addresses the following issues:
- Ignore single clicks. This was previously causing unexpected shifting of the focal point.
- Always set the zoom *after* setting the focal point so that the camera is aligned correctly.
- Remember the selected zoom until the user double-clicks to zoom out. Previously the camera was reset on each new time step with an available plot.
- Prevent the camera position from drifting over time as the user zooms in and out by remembering the original position and setting it again on zoom out.
Fixes #148

Zoom updates

---

client/src/components/widgets/ImageGallery/script.js
client/src/components/widgets/ImageGallery/template.html
client/src/scss/gallery.scss

Gives the VTK.js annotations a white background to make them pop.
There is apparently a known issue with keeping Plotly annotations aligned nicely. To get around this I am now using a new `span` element and simply position the text that way. Also has a white background now to make the text legible in the case where the annotation is forced to overlap other text (although this case should be less frequent now).

Improve annotations

---

client/src/components/core/App/script.js
client/src/components/core/App/template.html

Previously the slider would not update properly occasionally because it is only reactive to the value (the current time step) but that is updated before the min and max are sometimes. The value is now "computed" when the min/max are changed and so the slider is updated properly

Force slider to be reactive to min/max changes

---

client/src/components/core/App/script.js
client/src/components/widgets/ImageGallery/script.js
client/src/store/plots.js
client/src/store/views.js

Do not update the time step until all new images have been added. When loading a new image remove the renderer for Plotly plots if it exists or purge the Plotly plot for VTK plots if it exists.

Fix the load view option

---

client/src/components/widgets/ImageGallery/script.js

This should be reverted when vtk.js includes the axes labels in its bounds.

Hack the y bounds to include x axes label

---

client/src/components/widgets/ImageGallery/script.js

For now the option to toggle the log scaling is simply an addition to the modebar since it is only an option for Plotly plots at the moment.

Add an option to apply log scaling to Plotly plots

---

fastapi/app/api/api_v1/endpoints/images.py

Apply log scaling to saved images if the key exists and is set to true.

Remove "log" key if no scaling is applied

---

client/src/components/widgets/ContextMenu/script.js
client/src/components/widgets/ContextMenu/template.html
client/src/components/widgets/DownloadOptions/index.vue
client/src/components/widgets/DownloadOptions/script.js
client/src/components/widgets/DownloadOptions/template.html
client/src/store/ui.js
fastapi/app/api/api_v1/endpoints/images.py
fastapi/app/api/api_v1/endpoints/movie.py

- Add `Download Options` to context menu
- Add dialog with additional options for downloads:
- Download a zipped folder with a single time step, a range and/or list of time steps, or all available time steps as `png`s or `pdf`s
- Download a movie with all or a range and/or list of time steps as `mp4` or `mpg`

Extend movie/image download options

---

ingest/esimmon/cli/watch/__init__.py

When watch a HTTP site if we get a 404 we return None ....

Return None from file source if file doesn't exist

---

client/src/components/core/App/script.js
client/src/components/core/App/template.html
client/src/components/core/ViewControls/template.html
client/src/components/widgets/VTKPlot/script.js
client/src/scss/gallery.scss
client/src/utils/vtkPlotStyling.js

This cleans up a handful of appearance/layout issues:
- Prevent overlapping plots/scalarbars in VTK plots by enforcing a square viewport for our scaled (square) plots
- Resize the render window when the navigation panel is resized (otherwise VTK plots flow out of their cell)
- Resize the control panel to prevent flickering when updated (Fixes #172)
- Use consistent styling for the scalarbar in VTK plots (all titles are vertical now to avoid wasted space created by horizontal titles)

Cleanup plot appearances

---

client/src/components/widgets/PlotlyPlot/script.js
client/src/components/widgets/Plots/script.js
client/src/store/views.js
fastapi/app/api/api_v1/endpoints/images.py

Adds the ability to toggle the visibility of the legends on Plotly plots. Defaults to hidden.
Fizes #145

Hide the Plotly legends by default

---

client/src/components/core/App/script.js
client/src/components/widgets/Plots/script.js
client/src/components/widgets/VTKPlot/script.js
client/src/utils/constants.js
fastapi/app/api/api_v1/endpoints/images.py
fastapi/app/api/api_v1/endpoints/plotly.py
fastapi/app/api/api_v1/endpoints/scatter.py
fastapi/app/api/api_v1/endpoints/variables.py
fastapi/app/schemas/format.py

Adds support for transportation and Poincare plots.
Transportation plots:
Poincare:
There is some weird behavior for the axes for the `RZ` parameter, but this does not happen with the flux plots or `ThetaPsi` parameter (which have the same hacks applied to them to fix the plot ratio and adjust the axes actor). I will need to dig into this behavior more.

Transportation and Poincare plot support

---

client/src/components/widgets/Plots/script.js
client/src/store/plots.js

Fixes the following bugs:
- If the same VTK plot was added more than once the second plot was not rendered. This was because the plot type was not being set (we were not re-fetching the data and therefore not resetting the plot type) and the default type is Plotly, so the react() function was being called for the wrong plot type and nothing was rendered.
- If we moved back in time to a time step before the first available for a plot that plot remained at its current time step rather than moving back to the first available.
- Dropping collections/folders/etc should have no effect but they were being processed as items which would fail to update properly, creating bugs.
- The slider would always look weird on initial data load because the min value was being set before the max, so the …

Plot loading bugs

---

client/src/bootstrap.js
devops/ansible/site.yml
devops/docker/.env
devops/docker/docker-compose.ansible.yml
devops/docker/docker-compose.client.yml
devops/docker/docker-compose.demo.yml
devops/docker/docker-compose.fastapi.yml
devops/docker/docker-compose.girder.yml
devops/docker/docker-compose.watch-standalone.yml
devops/docker/docker-compose.watch.yml

- Remove checks for unused environment variables
- Fetch the default location starting folder id rather than hard-coding it. This means that we will no longer need different images for the NERSC and AWS deployments.
- Tag all of the containers with an initial `0.1.0` to match the current client version

Simplify containers

---

client/src/components/widgets/GirderDataBrowser/script.js
fastapi/app/api/api_v1/endpoints/movie.py
ingest/esimmon/cli/watch/__init__.py

Now when a run is being ingested we:
1. Create a new folder within the run for all movies
1. This follows the [same directory structure](https://github.com/bnmajor/adios-dashboard/blob/f40da9c2f1afd742ef3970fe2aca481d93733263/ingest/esimmon/cli/watch/__init__.py#L461-L465) as the run. We then [store the id](https://github.com/bnmajor/adios-dashboard/blob/f40da9c2f1afd742ef3970fe2aca481d93733263/ingest/esimmon/cli/watch/__init__.py#L467-L471) for the original item in the metadata on the movie item and vice versa (this saves search time for the client side).
3. Watch for the run to be [marked complete](https://github.com/bnmajor/adios-dashboard/blob/f40da9c2f1afd742ef3970fe2aca481d93733263/ingest/esimmon/cli/watch/__init__.py#L704)
4. Wait for any final images (`bp` files) to be [ingested …

Automatically generate movies

---

client/src/components/widgets/Plots/script.js

When averaging over time we need to have all plots loaded before averaging. Make sure that all steps in the range are either already loaded or are not available to load before progressing.

Fix logic for determining which plots are loaded

---

devops/docker/ingest/Dockerfile

When the container was updated to use conda the esimmon executable path changed.

Fix entrypoint path

---

client/package.json
client/src/components/widgets/RenderWindow/script.js
client/src/components/widgets/VTKPlot/script.js
client/src/utils/vtkCustomCubeAxesActor.js
client/src/utils/vtkPlotStyling.js
client/yarn.lock

Bump `vtk.js` version `22.6.1` -> `25.15.1`.
- There is a bug with the `vtkCubeAxesActor` in `v26.0.0` where axes labels are not always rendered correctly or at all. Until this can be investigated further and the issue pinned down we will pin to `v25.15.1` (the last available release where the bug is not seen).
- In `v24.0.0` some breaking changes were introduced that seem to affect the way events are captured and passed along. This PR adds new event handlers to catch double-click to zoom out as well as right-click for the context menu.
- We are now using scientific notation for the scalar bars so that text does not overlap the plots.

Bump vtkjs

---

client/src/components/core/App/template.html
client/src/components/core/ViewControls/script.js
client/src/components/core/ViewControls/template.html
client/src/components/widgets/PlotlyPlot/script.js
client/src/components/widgets/Plots/template.html
client/src/scss/gallery.scss

Adds a handful of improvements/cleanup:
- Disable plot time step selection after the step has been selected. To select a new step the feature will need to be re-enabled.
- Clean up the appearance of Plotly plots so that the do not hang over the edge of the card
- Make the splitpane divider easier to grab
- Cleanup the play controls so that everything is better aligned
Before:
After:

Improvements

---

ingest/esimmon/cli/watch/__init__.py

When data is being ingested we now also grab the min/max for the variables in the plot so that we can find the global min/max for a given run. This will allow us to produce plots using this range so that axes do not shift over time.
- For most variables we use [bpls](https://adios2.readthedocs.io/en/latest/ecosystem/utilities.html#bpls-inspecting-data) to just grab the min and max values for that time step. We compare these values to what we have saved in the item's metadata and update accordingly.
- The exception to this is for 2d mesh data. The min/max produced is overall rather for each dimension. For this case we actually open the file, grab the data, and parse the ranges before comparing and updating. 
This is the the first step that we need to implement in order to create simplified …

Set min/max info for vars as metadata

---

client/src/components/core/App/script.js
client/src/components/core/App/template.html
client/src/components/widgets/ContextMenu/script.js
client/src/components/widgets/ContextMenu/template.html
client/src/components/widgets/DownloadOptions/script.js
client/src/components/widgets/LoadDialog/script.js
client/src/components/widgets/PlotlyPlot/script.js
client/src/components/widgets/PlotlyPlot/template.html
client/src/components/widgets/Plots/script.js
client/src/components/widgets/SettingsPanel/script.js
client/src/components/widgets/SettingsPanel/template.html
client/src/components/widgets/VTKPlot/script.js
client/src/components/widgets/VTKPlot/template.html
client/src/scss/gallery.scss
client/src/store/plot.js
client/src/store/ui.js
client/src/store/views.js
client/src/utils/helpers.js
client/src/utils/vtkCustomCubeAxesActor.js
fastapi/app/api/api_v1/endpoints/images.py
fastapi/app/api/api_v1/endpoints/variables.py

~Relies on #282 for docs to pass~ :white_check_mark:  
This PR provides the following - 
Features:
- UI toggles for showing or hiding plot details (axis labels/tick marks, scalar bar, legend visibility)
- On ingest we use [`bpls`](https://adios2.readthedocs.io/en/latest/ecosystem/utilities.html#bpls-inspecting-data) and parse the string to grab the min/max ranges for the given variable and use this to update the metadata for that item. For mesh data we open the file to look at the mesh and find the min/max for each dimension.
- The option to apply a "global range" to the plots (uses the ranges for the completed run to prevent shifting axes/color range over time)
- New tooltip in the lower right that will display the ranges for any currently hidden data. This tooltip feature can also be …

Global range

---

devops/docker/fastapi/Dockerfile

Latest coninuumio/miniconda3 image produces the error "ImportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found". Conda install libstdcxx-ng=13.1.0 to prevent this error.

Update libstdcxx-ng version

---

client/src/components/core/App/script.js
client/src/components/widgets/ContextMenu/script.js
client/src/components/widgets/ContextMenu/template.html
client/src/components/widgets/PlotlyPlot/script.js
client/src/components/widgets/PlotlyPlot/template.html
client/src/components/widgets/Plots/script.js
client/src/components/widgets/Plots/template.html
client/src/components/widgets/SettingsPanel/script.js
client/src/components/widgets/SettingsPanel/template.html
client/src/components/widgets/StaticImage/index.vue
client/src/components/widgets/StaticImage/script.js
client/src/components/widgets/StaticImage/template.html
client/src/components/widgets/VTKPlot/script.js
client/src/components/widgets/VTKPlot/template.html
client/src/scss/gallery.scss
client/src/store/ui.js
client/src/utils/constants.js
client/src/utils/helpers.js
client/src/utils/plotFetcher.ts
client/tests/plotFetcher.spec.ts
devops/docker/fastapi/Dockerfile
fastapi/app/api/api_v1/endpoints/images.py
fastapi/app/api/api_v1/endpoints/movie.py
fastapi/app/api/api_v1/endpoints/variables.py
ingest/esimmon/cli/watch/__init__.py

Adds:
- When new data is ingested a "default" movie is produced when the run is complete. The images used in this movie generation are now also saved so that when we animate the dashboard in "fast" mode we stream the static images instead of dynamically generating the plot for each time step.
- Static images are now also ingested if they are listed in the `variables.json` file. The path for the attribute should be updated to point to the image instead of the BP file. The image is expected to be named `attribute_name`.`ext`, where `attribute_name` is the same as the string provided to the `attribute_name` key.
- Client-side support for static images has been added.
- If the requested variable does not exist in that time step's BP file or no BP file exists for that time step we look for a …

Fast plots
